### PR TITLE
Added italian translations

### PR DESCRIPTION
**Pull request by dariomalchiodi**
I have added Italian translations, where missing, and reviewed and corrected the existing ones.

### CODE REVIEW

**Comment by mmcky** [comment]
thank you @dariomalchiodi. Sorry it has taken a while to get to this.

**Comment by dariomalchiodi** [comment]
> thank you @dariomalchiodi. Sorry it has taken a while to get to this.

Don't worry and thanks for your valuable work! I look forward to see this merged in the main branch and use it for my italian lecture notes.

**Comment by mmcky** [comment]
thanks @dariomalchiodi. 

I will merge this into the main branch now. @AakashGfude can you think of a way we could add any tests for this?

@dariomalchiodi if your lectures are public would you mind adding the link to this PR. We could then generate a simple test case with Italian :-).

**Comment by dariomalchiodi** [comment]
> thanks @dariomalchiodi.
> 
> @dariomalchiodi if your lectures are public would you mind adding the link to this PR. We could then generate a simple test case with Italian :-).

Lectures are generated via a github action from a private repository, using jupyterbook and the pip version of sphinx-proof. The output is public at https://dariomalchiodi.github.io/sds (but this is still a very preliminary version!) although this is the generated HTML. If you need access to the markdown files is it fine for you if I grant you access to the original repo?

**Comment by AakashGfude** [comment]
@mmcky it will be hard to compare for each language. But we can verify the translation process itself, by running a test if the JSON is getting converted. Which we don't have here yet. Like in https://github.com/executablebooks/sphinx-book-theme/blob/master/tests/test_locale_convert.py

**Pull request merged**
