### PR TITLE
Added translation to Czech language

### PR DESCRIPTION
**Pull request by tomastalasek**
I have added Czech translation to the sphinx-proof.

PS. This is my first commit - I hope that I have done everything correctly.

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @tomastalasek for this PR. Sorry for the delay in getting back to you. 

Is there a simple example that we could add to the test cases?

**Comment by AakashGfude** [comment]
I guess we can just do the conversion part in one test case. Testing for each language will be a bit hectic. What do you think @mmcky? @tomastalasek can you update the branch with the latest master, so the test cases pass.

**Comment by tomastalasek** [comment]
Hi @AakashGfude Aska and @mmcky. I have updated the branch as requested. But I have a question the "test case". I am not sure, what I should do (as I stated, this is my first commit and I am more mathematician than programmer). Can you please give me hint? Thanks

**Comment by AakashGfude** [comment]
Hi @tomastalasek, thank you for updating. Don't worry we will not deal with a test case here. I will create a test case for translations in a separate PR.

**Comment by mmcky** [comment]
thanks @tomastalasek and @AakashGfude

**Pull request merged**
