### PR TITLE
MAINT: master to main, and various maintenance tasks

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates `master` to `main`

- [x] updates base python to `python=3.11` for all tests and tests `3.10` and `3.11`
- [x] removes netlify powered previews (as not required)
- [x] adds `github actions` dependabot
- [x] upgrades version pinnings for `tests` to run in more recent python context
- [x] updates text fixtures
- [x] update default branch name on github

### CODE REVIEW

**Comment by mmcky** [comment]
@agoose77 would you like to review or are you happy for me to merge this to start updating `sphinx-proof`?

**Comment by agoose77** [comment]
@mmcky can we install pre-commit.ci on this repo instead of using an action? (https://pre-commit.ci)

**Comment by mmcky** [comment]
> @mmcky can we install pre-commit.ci on this repo instead of using an action? (https://pre-commit.ci)

great idea @agoose77 -- happy to try and set this up tomorrow.

**Review by agoose77 — APPROVED** [review]

**Comment by mmcky** [comment]
@agoose77 I reverted [f556407](https://github.com/executablebooks/sphinx-proof/pull/99/commits/f5564074ff0410bb90b388bb210bbd8d419785d8) as I wasnt sure how to satisfy the pre-commit requirement in the publish workflow to `pypi`.

**Comment by mmcky** [comment]
thanks @agoose77 for your review. 👍

**Pull request merged**
