### PR TITLE
[ENH] Adding translations infrastructure and a word translation

### PR DESCRIPTION
**Pull request by vincentxavier**
This is a copy from
[sphinx-book-theme](https://github.com/executablebooks/sphinx-book-theme/tree/master/sphinx_book_theme/translations).

I'm a bit stuck about how translate only the words that appears in the produced documents while not changing the identifier used in source files.

### CODE REVIEW

**Comment by vincentxavier** [comment]
I think I've get the right place to put the translation.

**Comment by vincentxavier** [comment]
Have to rework `from . import _` since it creates a circular import

**Comment by vincentxavier** [comment]
I've now tested the translation on my personnal page. I just need to write some tests about the translation, and translate the other strings.

**Comment by AakashGfude** [comment]
> I've now tested the translation on my personnal page. I just need to write some tests about the translation, and translate the other strings.

Hi, @vincentxavier thank you for putting this together. Let us know when you write the tests. Also, the link to your personal page to test the translation would be helpful.

**Comment by AakashGfude** [comment]
Thank you, @vincentxavier , this PR looks good to go. I feel like this line is not necessary for that file https://github.com/executablebooks/sphinx-proof/pull/71/files#diff-1a6b6a088ee724e8830ef4cb8137c12280dcfe891868bcf44ee7d8d1b24926c5R30 . But we can reiterate in follow-up PRs. I will go ahead and merge this one.
Thanks a lot again for adding translations.

**Comment by dtenbrinck** [comment]
Thank you for your contribution! I was looking for exactly this feature and I am happy you implemented translations for `sphinx-proof`.
Is there a reason, why the directory `jsons` is not included in the current **pip package** of version 0.2.0? I had to download the directory from this repository and include it manually to get translations of the proof directives to work.

**Pull request merged**
